version: '3.3'

services: 
  web:
    build: ./celerytask
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./celerytask:/usr/src/app
    ports: 
      - 8000:8000
    environment: 
      - DEBUG=1

      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on: 
      - redis

  celery:
    build: ./celerytask
    command: celery worker --app=core --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./celerytask:/usr/src/app
    environment:
      - DEBUG=1
      
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      
    depends_on: 
      - web
      - redis
  
  redis:
    image: redis:6-alpine